language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - COMPOSER_FLAGS=""
  - COMPOSER_FLAGS="--prefer-lowest"

sudo: false

install:
  - wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update -n
  - composer update $COMPOSER_FLAGS

  - features/fixtures/project/app/console assets:install features/fixtures/project/web --relative --symlink

  # Run php builtin server
  - nohup php -S 127.0.0.1:8080 -t features/fixtures/project/web > server.log 2>&1 &

  # Run selenium
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - java -jar selenium-server-standalone-2.44.0.jar > selenium.log 2>&1 &
  - sleep 5

script:
  - bin/phpspec run -v -f dot
  - bin/behat --no-snippets --verbose --format=progress --profile=travis -vvv

notifications:
  irc: "irc.freenode.org#fsi-open"
