language: php

sudo: false

matrix:
    include:
      - php: 7.1
        env:
          - COMPOSER_FLAGS="--prefer-lowest"
      - php: 7.1

addons:
    firefox: "47.0.1"

install:
    - phpenv config-rm xdebug.ini
    - composer update $COMPOSER_FLAGS
    - wget --no-clobber -O bin/selenium.jar http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar || true

before_script:
    - nohup php -S localhost:8080 -t features/fixtures/project/web > /dev/null 2>&1 &
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - java -jar bin/selenium.jar > /dev/null 2>&1 &
    - sleep 5
    - features/fixtures/project/app/console assets:install features/fixtures/project/web --relative --symlink

script:
    - bin/phpspec run -v -f dot
    - bin/behat --no-snippets --verbose --format=progress --profile=travis
