language: php

sudo: true

matrix:
    include:
      - php: 7.1
        env:
          - COMPOSER_FLAGS="--prefer-lowest"
      - php: 7.4
      - php: 8.0

env:
  global:
    - SYMFONY_ENV=test

addons:
    firefox: "47.0.1"

services:
    - xvfb

install:
    - phpenv config-rm xdebug.ini
    - COMPOSER_MEMORY_LIMIT=-1 composer update $COMPOSER_FLAGS
    - wget --no-clobber -O vendor/bin/selenium.jar http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar || true

before_script:
    - nohup php -S localhost:8080 -t features/fixtures/project/web > server.log 2>&1 &
    - java -jar vendor/bin/selenium.jar > /dev/null 2>&1 &
    - sleep 5
    - features/fixtures/project/app/console assets:install features/fixtures/project/web --relative --symlink

script:
    - vendor/bin/phpspec run -v -f dot -n
    - vendor/bin/behat --no-snippets --verbose --format=progress --profile=travis

after_failure:
    - cat /tmp/FSiFormExtensionsBundle/logs/test.log
    - cat server.log
