language: php

matrix:
    include:
      - php: 7.4
        env:
          - COMPOSER_FLAGS="--prefer-lowest"
      - php: 8.0
      - php: 8.1

env:
  global:
    - APP_ENV=test
      COMPOSER_MEMORY_LIMIT=-1

addons:
    firefox: "47.0.1"

services:
    - xvfb

install:
    - phpenv config-rm xdebug.ini
    - composer validate
    - composer update $COMPOSER_FLAGS
    - composer cache-clear
    - wget --no-clobber -O vendor/bin/selenium.jar http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar || true

before_script:
    - nohup php -S localhost:8080 -t features/fixtures/project/public > server.log 2>&1 &
    - java -jar vendor/bin/selenium.jar > /dev/null 2>&1 &
    - sleep 5
    - composer assets

script:
    - vendor/bin/phpcs
    - vendor/bin/phpstan analyze -c phpstan.neon
    - vendor/bin/phpspec run -v -f dot -n
    - vendor/bin/behat --no-snippets --verbose --format=progress --profile=travis

after_failure:
    - cat features/fixtures/project/var/logs/test.log
    - cat server.log
