name: Tests

on:
    push:
        branches:
          - 'master'
          - '2.4'
          - '2.3'
          - '2.2'
          - '2.1'
          - '2.0'
          - '1.1'
          - '1.0'
    pull_request:
    workflow_dispatch:

jobs:
    test:
        strategy:
            matrix:
                php-version: [8.1, 8.2, 8.3, 8.4]
        runs-on: ubuntu-22.04
        container:
            image: fsiopenpl/docker-php-apache:alpine-${{ matrix.php-version }}
            env:
                COMPOSER_FLAGS: ${{ matrix.php-version == '8.1' && ' --prefer-lowest' || '' }}
        timeout-minutes: 10
        steps:
            - name: Checkout source
              uses: actions/checkout@v1
            - name: Validate composer config
              run: composer validate
            - name: Install dependencies
              run: composer update ${COMPOSER_FLAGS}
            - name: Install assets
              run: composer assets
            - name: Install selenium
              run: wget --no-clobber -O vendor/bin/selenium.jar http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar || true
            - name: Code quality
              run: vendor/bin/phpcs
            - name: Code static analysis
              run: composer stan
            - name: Unit tests
              run: vendor/bin/phpspec run -v -f dot -n
            - name: Start background processes
              run: |
                nohup php -S localhost:8080 -t features/fixtures/project/public > server.log 2>&1 &
                java -jar vendor/bin/selenium.jar > /dev/null 2>&1 &
                sleep 5
            - name: Functional tests
              run: vendor/bin/behat --no-snippets --verbose --format=progress --profile=travis --tags ~@google-maps
